config/routes.rb
Rails.application.routes.draw do
  resources :followers
  resources :profiles

  devise_for :users

  resources :photos do
    resources :comments
    member do
      put 'like', to: 'photos#like'
      put 'dislike', to: 'photos#dislike'
    end
  end

  resources :users do
    member do
      put 'follow', to: 'users#follow'
    end
  end

  get 'profile', to: 'profiles#current'

  root to: 'pages#homepage'
  # get 'users/sign_out', to: 'pages#homepage'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment

  def index
    @comment = Comment.new
  end

  # def create
  #   @photo = Photo.find(params[:photo_id])
  #   @comment = @photo.comments.create(comment_params)
  #   redirect_to photos_path
  # end

  def create
    @comment = @photo.comments

    @new_comment = Comment.new(comment_params)

    @new_comment.user = current_user

    @new_comment.photo = @photo

    @new_comment.save!

    redirect_to photos_path
  end

  def edit
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
  end

  def update

  end

  private

    def set_comment
      @comment = Comment.find(params[:message])
    end

    def comment_params
      params.require(:comment).permit(:message)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<%# puts "-----#{locals[:photo].inspect}" %>
<%# puts "-----#{locals[:comment].inspect}" %>

<%= form_with(model: [locals[:photo], locals[:comment]], local: true, url: photo_comments_path(locals[:photo].id)) do |form| %>
  <div class="field">
    <%= form.label :message %><br>
    <%= form.text_area :message %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>