config/routes.rb
Rails.application.routes.draw do
  resources :followers
  resources :profiles

  devise_for :users

  resources :photos do
    resources :comments
    member do
      put 'like', to: 'photos#like'
      put 'dislike', to: 'photos#dislike'
    end
  end

  resources :users do
    member do
      put 'follow', to: 'users#follow'
    end
  end

  get 'profile', to: 'profiles#current'

  root to: 'pages#homepage'
  # get 'users/sign_out', to: 'pages#homepage'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  acts_as_votable

  has_many :comments

  include PhotoUploader::Attachment.new(:image)

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :like, :dislike]

# Photo.where(user: user.followers)



  def index
    # if the url is /photos?following
    if params.has_key?(:following)

      # @user = User.find(params[:id])

      # @photos = Photo.where(user: @user.followers)



# =begin
      # create an array to hold the photos we want to show (i.e those from users the current user is following)
      @photos = []

      # for each user that the current user is following, add the array of their photos to "@photos"
      current_user.following.each do |followee|
        @photos << followee.photos
      end
      # flatten "@photos" to be a one-dimensional array of all photos from all users followed by current user
      @photos.flatten!
# =end

    # if the url is /photos, show all photos from all users
    else
      @photos = Photo.all
      @comment = Comment.new
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    if @photo.user == current_user
      respond_to do |format|
        if @photo.update(photo_params)
          format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
          format.json { render :show, status: :ok, location: @photo }
        else
          format.html { render :edit }
          format.json { render json: @photo.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    if @photo.user == current_user
      @photo.destroy
      respond_to do |format|
        format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def like
    if current_user.liked?(@photo)
      @photo.unvote_by current_user
    else
      @photo.liked_by current_user
    end

    redirect_to photos_path
  end

  def dislike
    if current_user.disliked?(@photo)
      @photo.unvote_by current_user
    else
      @photo.disliked_by current_user
    end

    redirect_to photos_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through. PHOTOS
    def photo_params
      params.require(:photo).permit(:caption, :image, :following)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption, id: :photo_caption %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.hidden_field :image, value: photo.cached_image_data %>
    <%= form.file_field :image, id: :photo_image_data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col pb-4 text-center">
      <h1>Photos</h1>
    </div>
  </div>

  <div class="row">
    <div class="col text-center">
      <%= link_to 'New Photo', new_photo_path %>
    </div>
  </div>

  <% @photos.each do |photo| %>
    <div class="container text-center mt-3 pb-3 photo-container rounded">
      <div class="row">
        <div class="col-12">
          <%= image_tag photo.image_url, class: "image-full-size" %>
        </div>
      </div>
      <div class="row">
        <div class="col">

          <div class="row">
            <div class="col image-caption">
              <%= photo.caption %>
            </div>
          </div>

          <div class="row pt-5 pb-5">
            <div class="col d-flex justify-content-end font-weight-bold">

              <%= link_to profile_path(photo.user) do %>
                <%= photo.user.email %>
              <% end %>

            </div>
            <div class="col d-flex justify-content-start">
              <%= button_to follow_user_path(photo.user), method: "put", class: "btn btn-info" do %>

                <% if current_user.following?(photo.user) %>
                  Unfollow
                <% else %>
                  Follow
                <% end %>

              <% end %>
            </div>
          </div>

        </div>
      </div>

      <div class="row">
        <div class="col">

          <%= button_to like_photo_path(photo), method: "put", class: "btn btn-success" do %>

            <span><%= photo.get_likes.size %></span> Likes

          <% end %>

        </div>
        <div class="col">

          <%= button_to dislike_photo_path(photo), method: "put", class: "btn btn-danger" do %>

            <span><%= photo.get_dislikes.size %></span> Dislikes

          <% end %>

        </div>
      </div>

      <div class="row">
        <div class="col text-center">

          <!-- form to add comment -->
          <%= render 'comments/comments', locals: { :comment => @comment, :photo => photo } %>

        </div>
      </div>

      <div class="row">
        <div class="col">
          <%#= link_to 'View', photo %>
          <% if photo.user == current_user %>
            <%= link_to 'Edit', edit_photo_path(photo) %>
            <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <br>

</div>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<div class="container text-center">
  <p id="notice"><%= notice %></p>

  <div class="row">
    <div class="col">
      <%= image_tag @photo.image_url, class: "image-full-size" %>
    </div>
  </div>

  <div class="row pt-3 pb-5">
    <div class="col font-weight-bold image-caption">
      <%= @photo.caption %>
    </div>
  </div>

  <div class="row">
    <div class="col pb-5">
      <%= link_to 'Edit', edit_photo_path(@photo) %> |
      <%= link_to 'Back', photos_path %>
    </div>
  </div>

</div>